jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8082
   servlet:
      context-path: /reserva
      session:
         timeout: 21600s

spring:
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://localhost:3308/reservas
      username: root
      password: root
      hikari:
         poolName: pool
